"""
Shopify Uploader — creates products on Shopify store via REST Admin API.
Uses client_credentials flow for authentication.
"""

import os
import json
import base64
import time
import requests


BUNDLE_TEMPLATE_LIQUID = '''{% comment %}
  Bundle Product Template — Custom Options via Line Item Properties
  Auto-generated by Product Automation Tool
{% endcomment %}

{{ 'bundle-options.css' | asset_url | stylesheet_tag }}

<div class="bundle-product" id="bundle-product" data-product-id="{{ product.id }}">
  <div class="bundle-product__grid">
    
    {%- comment -%} Images {%- endcomment -%}
    <div class="bundle-product__images">
      {% for image in product.images %}
        <div class="bundle-product__image {% if forloop.first %}bundle-product__image--active{% endif %}" data-index="{{ forloop.index0 }}">
          <img src="{{ image | image_url: width: 800 }}" alt="{{ image.alt | default: product.title }}" loading="{% if forloop.first %}eager{% else %}lazy{% endif %}">
        </div>
      {% endfor %}
      {% if product.images.size > 1 %}
        <div class="bundle-product__thumbs">
          {% for image in product.images %}
            <button class="bundle-product__thumb {% if forloop.first %}bundle-product__thumb--active{% endif %}" data-index="{{ forloop.index0 }}">
              <img src="{{ image | image_url: width: 100 }}" alt="">
            </button>
          {% endfor %}
        </div>
      {% endif %}
    </div>

    {%- comment -%} Product Info {%- endcomment -%}
    <div class="bundle-product__info">
      <h1 class="bundle-product__title">{{ product.title }}</h1>
      
      <div class="bundle-product__price" id="bundle-price">
        <span class="bundle-product__price-label">From</span>
        <span class="bundle-product__price-amount" id="bundle-total-price">
          {{ product.price | money }}
        </span>
        <span class="bundle-product__price-tax">inc. VAT</span>
      </div>

      <form method="post" action="/cart/add" id="bundle-form">
        <input type="hidden" name="id" value="{{ product.variants.first.id }}">
        
        <div class="bundle-options" id="bundle-options">
          {%- comment -%} Options rendered by JS from metafield {%- endcomment -%}
          <div class="bundle-options__loading">Loading options...</div>
        </div>

        <div class="bundle-product__qty">
          <label for="bundle-qty">Quantity</label>
          <div class="bundle-product__qty-wrap">
            <button type="button" class="bundle-product__qty-btn" data-action="decrease">−</button>
            <input type="number" name="quantity" id="bundle-qty" value="1" min="1">
            <button type="button" class="bundle-product__qty-btn" data-action="increase">+</button>
          </div>
        </div>

        <button type="submit" class="bundle-product__add-btn" id="bundle-add-btn">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
          Add to Cart — <span id="bundle-btn-price">{{ product.price | money }}</span>
        </button>
      </form>

      <div class="bundle-product__description">
        {{ product.description }}
      </div>
    </div>
  </div>
</div>

<script>
(function(){
  var metaTag = document.querySelector(\'meta[name="bundle-config"]\');
  var configRaw = null;
  var basePriceRaw = null;
  
  // Fetch metafields via product JSON
  fetch(window.location.pathname + \'.json\')
    .then(function(r){ return r.json(); })
    .then(function(data){
      // Try to get metafields from product JSON or use the API
      loadBundleConfig();
    })
    .catch(function(){ loadBundleConfig(); });

  function loadBundleConfig(){
    // Fetch metafields
    fetch(\'/products/\' + document.getElementById(\'bundle-product\').dataset.productId + \'.json\')
      .then(function(r){ return r.json(); })
      .catch(function(){});
    
    // Use storefront API to get metafields
    var handle = window.location.pathname.split(\'/\').pop();
    fetch(\'/products/\' + handle + \'.js\')
      .then(function(r){ return r.json(); })
      .then(function(product){
        // Look for bundle config in metafields
        if(product.metafields && product.metafields.custom_options){
          renderOptions(JSON.parse(product.metafields.custom_options.bundle_config));
        }
      })
      .catch(function(){
        // Fallback: try liquid-rendered approach
        tryLiquidApproach();
      });
  }

  function tryLiquidApproach(){
    var el = document.getElementById(\'bundle-config-data\');
    if(el){
      try {
        renderOptions(JSON.parse(el.textContent));
      } catch(e){}
    }
  }

  function renderOptions(options){
    if(!options || !options.length) return;
    var container = document.getElementById(\'bundle-options\');
    container.innerHTML = \'\';
    var basePrice = parseFloat(document.getElementById(\'bundle-total-price\').textContent.replace(/[^0-9.]/g, \'\')) || 0;
    
    options.forEach(function(opt, idx){
      var div = document.createElement(\'div\');
      div.className = \'bundle-option\';
      if(opt.type === \'colour_swatch\'){
        div.classList.add(\'bundle-option--swatch\');
        div.innerHTML = \'<label class="bundle-option__label">\' + opt.title + \'</label>\' +
          \'<div class="bundle-option__swatches" id="swatch-\' + idx + \'">\' +
          opt.items.map(function(item, i){
            var colorHex = getRALColor(item.name);
            return \'<button type="button" class="bundle-swatch" data-value="\' + item.name + \'" data-price="\' + item.price_adjustment + \'" \' +
              \'style="background:\' + colorHex + \'" title="\' + item.name + \'"></button>\';
          }).join(\'\') + \'</div>\' +
          \'<input type="hidden" name="properties[_\' + opt.title + \']" class="bundle-option-input" data-option-idx="\' + idx + \'">\' +
          \'<span class="bundle-option__selected" id="swatch-label-\' + idx + \'">Select a colour</span>\';
      } else {
        div.innerHTML = \'<label class="bundle-option__label" for="opt-\' + idx + \'">\' + opt.title + \'</label>\' +
          \'<select class="bundle-option__select" id="opt-\' + idx + \'" name="properties[_\' + opt.title + \']" data-option-idx="\' + idx + \'" required>\' +
          \'<option value="">Choose...</option>\' +
          opt.items.map(function(item){
            var priceText = item.price_adjustment > 0 ? \' (+\\u00a3\' + item.price_adjustment.toFixed(2) + \')\' : \'\';
            return \'<option value="\' + item.name + \'" data-price="\' + item.price_adjustment + \'">\' + item.name + priceText + \'</option>\';
          }).join(\'\') + \'</select>\';
      }
      container.appendChild(div);
    });

    // Handle conditional visibility (hide colours when Galvanised Only)
    var finishSelect = container.querySelector(\'select[name*="Finish"]\');
    var colourOption = container.querySelector(\'.bundle-option--swatch\');
    if(finishSelect && colourOption){
      function toggleColours(){
        var val = finishSelect.value.toLowerCase();
        colourOption.style.display = (val.indexOf(\'galvanised only\') !== -1 || !val) ? \'none\' : \'block\';
      }
      finishSelect.addEventListener(\'change\', toggleColours);
      toggleColours();
    }

    // Swatch click
    container.querySelectorAll(\'.bundle-swatch\').forEach(function(btn){
      btn.addEventListener(\'click\', function(){
        var parent = btn.closest(\'.bundle-option\');
        parent.querySelectorAll(\'.bundle-swatch\').forEach(function(b){ b.classList.remove(\'bundle-swatch--active\'); });
        btn.classList.add(\'bundle-swatch--active\');
        parent.querySelector(\'.bundle-option-input\').value = btn.dataset.value;
        var idx = parent.querySelector(\'.bundle-option-input\').dataset.optionIdx;
        document.getElementById(\'swatch-label-\' + idx).textContent = btn.dataset.value;
        recalcPrice();
      });
    });

    // Select change
    container.querySelectorAll(\'select\').forEach(function(sel){
      sel.addEventListener(\'change\', recalcPrice);
    });

    function recalcPrice(){
      var total = basePrice;
      container.querySelectorAll(\'select\').forEach(function(sel){
        var opt = sel.selectedOptions[0];
        if(opt && opt.dataset.price) total += parseFloat(opt.dataset.price) || 0;
      });
      container.querySelectorAll(\'.bundle-swatch--active\').forEach(function(btn){
        total += parseFloat(btn.dataset.price) || 0;
      });
      var formatted = \'\\u00a3\' + total.toFixed(2);
      document.getElementById(\'bundle-total-price\').textContent = formatted;
      document.getElementById(\'bundle-btn-price\').textContent = formatted;
    }
  }

  function getRALColor(name){
    var colors = {
      \'1000\':\'#BEBD7F\',\'1018\':\'#F8F32B\',\'1023\':\'#FAD201\',\'3000\':\'#AF2B1E\',\'3003\':\'#9B111E\',
      \'3005\':\'#5E2129\',\'3020\':\'#CC0605\',\'5002\':\'#20214F\',\'5005\':\'#1B5583\',\'5013\':\'#1E213D\',
      \'5015\':\'#2271B3\',\'5017\':\'#063971\',\'6002\':\'#316650\',\'6005\':\'#2F4538\',\'6009\':\'#31372B\',
      \'6024\':\'#308446\',\'6029\':\'#20603D\',\'7005\':\'#6C7059\',\'7012\':\'#4E5754\',\'7016\':\'#293133\',
      \'7032\':\'#B8B799\',\'7047\':\'#D0D0D0\',\'8011\':\'#5B3A29\',\'9005\':\'#0A0A0A\',\'9010\':\'#FFFFFF\',
      \'9016\':\'#F7F7F7\'
    };
    var match = name.match(\/RAL\\s*(\\d+)\/i);
    if(match && colors[match[1]]) return colors[match[1]];
    return \'#ccc\';
  }

  // Quantity buttons
  document.querySelectorAll(\'.bundle-product__qty-btn\').forEach(function(btn){
    btn.addEventListener(\'click\', function(){
      var input = document.getElementById(\'bundle-qty\');
      var val = parseInt(input.value) || 1;
      input.value = btn.dataset.action === \'increase\' ? val + 1 : Math.max(1, val - 1);
    });
  });

  // Image gallery
  document.querySelectorAll(\'.bundle-product__thumb\').forEach(function(thumb){
    thumb.addEventListener(\'click\', function(){
      var idx = thumb.dataset.index;
      document.querySelectorAll(\'.bundle-product__image\').forEach(function(img){ img.classList.remove(\'bundle-product__image--active\'); });
      document.querySelectorAll(\'.bundle-product__thumb\').forEach(function(t){ t.classList.remove(\'bundle-product__thumb--active\'); });
      document.querySelector(\'.bundle-product__image[data-index="\' + idx + \'"]\').classList.add(\'bundle-product__image--active\');
      thumb.classList.add(\'bundle-product__thumb--active\');
    });
  });
})();
</script>

{%- comment -%} Inject bundle config from metafield {%- endcomment -%}
{% assign bundle_config = product.metafields.custom_options.bundle_config %}
{% if bundle_config %}
  <script id="bundle-config-data" type="application/json">{{ bundle_config }}</script>
{% endif %}
'''

BUNDLE_CSS = '''/* Bundle Product Template */
.bundle-product{max-width:1200px;margin:0 auto;padding:20px}
.bundle-product__grid{display:grid;grid-template-columns:1fr 1fr;gap:40px}
@media(max-width:768px){.bundle-product__grid{grid-template-columns:1fr}}
.bundle-product__images{position:sticky;top:20px}
.bundle-product__image{display:none}
.bundle-product__image--active{display:block}
.bundle-product__image img{width:100%;border-radius:8px}
.bundle-product__thumbs{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}
.bundle-product__thumb{width:60px;height:60px;border:2px solid #e0e0e0;border-radius:6px;overflow:hidden;cursor:pointer;padding:0;background:none}
.bundle-product__thumb--active{border-color:#333}
.bundle-product__thumb img{width:100%;height:100%;object-fit:cover}
.bundle-product__title{font-size:28px;font-weight:700;margin:0 0 16px;line-height:1.2}
.bundle-product__price{display:flex;align-items:baseline;gap:8px;margin-bottom:24px;padding:16px;background:#f8f8f8;border-radius:8px}
.bundle-product__price-label{font-size:14px;color:#666}
.bundle-product__price-amount{font-size:32px;font-weight:800;color:#1a1a1a}
.bundle-product__price-tax{font-size:12px;color:#888}
.bundle-option{margin-bottom:20px}
.bundle-option__label{display:block;font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px;color:#333}
.bundle-option__select{width:100%;padding:12px 14px;border:2px solid #e0e0e0;border-radius:6px;font-size:15px;background:#fff;cursor:pointer;transition:border-color .2s}
.bundle-option__select:focus{border-color:#333;outline:none}
.bundle-option__swatches{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:6px}
.bundle-swatch{width:36px;height:36px;border-radius:50%;border:3px solid #e0e0e0;cursor:pointer;transition:transform .15s,border-color .15s;padding:0}
.bundle-swatch:hover{transform:scale(1.15);border-color:#888}
.bundle-swatch--active{border-color:#333;transform:scale(1.15);box-shadow:0 0 0 2px #fff,0 0 0 4px #333}
.bundle-option__selected{font-size:13px;color:#666;font-style:italic}
.bundle-product__qty{margin:24px 0}
.bundle-product__qty label{display:block;font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px;color:#333}
.bundle-product__qty-wrap{display:flex;align-items:center;border:2px solid #e0e0e0;border-radius:6px;width:fit-content;overflow:hidden}
.bundle-product__qty-btn{width:40px;height:44px;border:none;background:#f5f5f5;cursor:pointer;font-size:18px;font-weight:700;color:#333;transition:background .15s}
.bundle-product__qty-btn:hover{background:#e0e0e0}
.bundle-product__qty-wrap input{width:60px;text-align:center;border:none;font-size:16px;font-weight:600;-moz-appearance:textfield}
.bundle-product__qty-wrap input::-webkit-inner-spin-button{-webkit-appearance:none}
.bundle-product__add-btn{display:flex;align-items:center;justify-content:center;gap:10px;width:100%;padding:16px;border:none;background:#1a1a1a;color:#fff;font-size:16px;font-weight:700;border-radius:8px;cursor:pointer;transition:background .2s,transform .1s;text-transform:uppercase;letter-spacing:.05em}
.bundle-product__add-btn:hover{background:#333}
.bundle-product__add-btn:active{transform:scale(.98)}
.bundle-product__description{margin-top:32px;line-height:1.7;color:#444}
.bundle-product__description h2,.bundle-product__description h3{color:#1a1a1a;margin-top:24px}
.bundle-product__description table{width:100%;border-collapse:collapse;margin:16px 0}
.bundle-product__description td,.bundle-product__description th{padding:10px 14px;border:1px solid #e0e0e0;text-align:left}
.bundle-product__description th{background:#f5f5f5;font-weight:700}
'''


class ShopifyUploader:
    def __init__(self, store=None, client_id=None, client_secret=None):
        self.store = store or os.getenv("SHOPIFY_STORE")
        self.client_id = client_id or os.getenv("SHOPIFY_CLIENT_ID")
        self.client_secret = client_secret or os.getenv("SHOPIFY_CLIENT_SECRET")
        self.access_token = None
        self.base_url = f"https://{self.store}/admin/api/2024-10"

    def authenticate(self):
        """Get access token via client_credentials."""
        resp = requests.post(
            f"https://{self.store}/admin/oauth/access_token",
            json={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
            },
            timeout=30,
        )
        resp.raise_for_status()
        self.access_token = resp.json()["access_token"]
        return self.access_token

    def _headers(self):
        if not self.access_token:
            self.authenticate()
        return {
            "X-Shopify-Access-Token": self.access_token,
            "Content-Type": "application/json",
        }

    def create_product(self, listing_data, images=None):
        """
        Create a product on Shopify from the AI-generated listing data.
        listing_data: dict with title, body_html, product_type, tags, variants, options
        images: list of dicts with 'data' (bytes) and 'filename'
        """
        # Build product payload
        product = {
            "title": listing_data["title"],
            "body_html": listing_data["body_html"],
            "product_type": listing_data.get("product_type", ""),
            "tags": ", ".join(listing_data.get("tags", [])),
            "status": "draft",
        }

        # Options
        if listing_data.get("options"):
            product["options"] = listing_data["options"]

        # Variants
        if listing_data.get("variants"):
            product["variants"] = []
            for v in listing_data["variants"]:
                variant = {
                    "option1": v.get("option1", "Default"),
                    "price": str(v.get("price", "0.00")),
                    "sku": v.get("sku", ""),
                    "inventory_management": None,
                    "inventory_policy": "continue",
                    "requires_shipping": True,
                    "taxable": True,
                }
                if v.get("option2"):
                    variant["option2"] = v["option2"]
                if v.get("option3"):
                    variant["option3"] = v["option3"]
                product["variants"].append(variant)

        # Images (base64 encoded)
        if images:
            product["images"] = []
            for i, img in enumerate(images):
                img_data = {
                    "attachment": base64.b64encode(img["data"]).decode("utf-8"),
                    "filename": img.get("filename", f"product-{i+1}.png"),
                }
                if i == 0:
                    img_data["position"] = 1
                product["images"].append(img_data)

        # Create product
        resp = requests.post(
            f"{self.base_url}/products.json",
            headers=self._headers(),
            json={"product": product},
            timeout=60,
        )

        if resp.status_code == 401:
            # Token expired, re-auth and retry
            self.authenticate()
            resp = requests.post(
                f"{self.base_url}/products.json",
                headers=self._headers(),
                json={"product": product},
                timeout=60,
            )

        resp.raise_for_status()
        created = resp.json()["product"]
        
        # If bundle product, add metafields with options and assign template
        if listing_data.get("bundle_options"):
            product_id = created["id"]
            
            # Save bundle options as metafield
            self._create_metafield(
                product_id,
                "custom_options",
                "bundle_config",
                json.dumps(listing_data["bundle_options"]),
                "json"
            )
            
            # Save base price as metafield
            if listing_data.get("base_price"):
                self._create_metafield(
                    product_id,
                    "custom_options",
                    "base_price",
                    str(listing_data["base_price"]),
                    "single_line_text_field"
                )
            
            # Assign custom template
            try:
                requests.put(
                    f"{self.base_url}/products/{product_id}.json",
                    headers=self._headers(),
                    json={"product": {"id": product_id, "template_suffix": "bundle"}},
                    timeout=30,
                )
            except Exception:
                pass
        
        return {
            "id": created["id"],
            "title": created["title"],
            "handle": created["handle"],
            "status": created["status"],
            "variants_count": len(created.get("variants", [])),
            "images_count": len(created.get("images", [])),
            "admin_url": f"https://{self.store}/admin/products/{created['id']}",
            "is_bundle": bool(listing_data.get("bundle_options")),
        }

    def _create_metafield(self, product_id, namespace, key, value, value_type):
        """Create a metafield on a product."""
        try:
            requests.post(
                f"{self.base_url}/products/{product_id}/metafields.json",
                headers=self._headers(),
                json={
                    "metafield": {
                        "namespace": namespace,
                        "key": key,
                        "value": value,
                        "type": value_type,
                    }
                },
                timeout=30,
            )
        except Exception:
            pass

    def ensure_bundle_template(self):
        """Create the bundle product template on the store if it doesn't exist."""
        try:
            # Get main theme
            resp = requests.get(
                f"{self.base_url}/themes.json",
                headers=self._headers(),
                timeout=30,
            )
            resp.raise_for_status()
            themes = resp.json()["themes"]
            main_theme = next((t for t in themes if t["role"] == "main"), None)
            if not main_theme:
                return
            
            theme_id = main_theme["id"]
            
            # Check if template already exists
            check = requests.get(
                f"{self.base_url}/themes/{theme_id}/assets.json",
                headers=self._headers(),
                params={"asset[key]": "templates/product.bundle.liquid"},
                timeout=30,
            )
            if check.status_code == 200:
                return  # Already exists
            
            # Create the bundle template
            template_content = BUNDLE_TEMPLATE_LIQUID
            requests.put(
                f"{self.base_url}/themes/{theme_id}/assets.json",
                headers=self._headers(),
                json={
                    "asset": {
                        "key": "templates/product.bundle.liquid",
                        "value": template_content,
                    }
                },
                timeout=30,
            )
            
            # Also create the CSS
            requests.put(
                f"{self.base_url}/themes/{theme_id}/assets.json",
                headers=self._headers(),
                json={
                    "asset": {
                        "key": "assets/bundle-options.css",
                        "value": BUNDLE_CSS,
                    }
                },
                timeout=30,
            )
        except Exception:
            pass

    def get_product_count(self):
        """Get total product count."""
        resp = requests.get(
            f"{self.base_url}/products/count.json",
            headers=self._headers(),
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()["count"]
